services:
  api:
    container_name: dinheiros-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app
    labels:
      # zerolog don't support send to loki
      # using promtail to get from container
      logging: "promtail"
    profiles:
      - all
      - app

  db:
    container_name: dinheiros-db
    image: postgres:16.2-alpine3.19
    volumes:
      - ./.docker/postgres:/data/postgres
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app
    profiles:
      - all
      - app

  # Telemetry
  blackbox:
    # used for healthcheck application
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.26.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      - app
    profiles:
      # - all
      - otel

  otel-lgtm:
    # whole grafana stack <3
    # https://github.com/grafetryana/docker-otel-lgtm/releases
    image: grafana/otel-lgtm:0.11.1
    container_name: otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      # loki port (so promtail can send logs)
      - "3100:3100"
    depends_on:
      blackbox:
        condition: "service_started"
        required: false
    volumes:
      - ./prometheus.yml:/otel-lgtm/prometheus.yaml
      - .docker/grafana/provisioning:/otel-lgtm/grafana/conf/provisioning
      - .docker/grafana-data:/data
    networks:
      - app
    profiles:
      - all
      - otel

  promtail:
    # get logs from containers
    image: grafana/promtail:3.2.1
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - app
    depends_on:
      - otel-lgtm
      - api
    profiles:
      - all
      - otel

volumes:
     postgres:

networks:
  app:
    driver: bridge
