FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Hot reload
RUN go install github.com/air-verse/air@latest

CMD air --build.cmd "go build -o bin/api ./cmd/api/" --build.bin "./bin/api"
