server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://otel-lgtm:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_logging']
        action: keep
        regex: promtail
      - source_labels: ['__meta_docker_container_name']
        target_label: container
